### ISSUE TITLE
API Key should not be public

### ISSUE THREAD

**Issue by FlorianLudwig** [tr4n2uil/python-browserstack#1]
https://github.com/tr4n2uil/python-browserstack/blob/master/test.py#L4 (not tried if it is an active key though)

**Comment by tr4n2uil** [comment]
Thanks! 
Fixed in [e7f6b1f](https://github.com/tr4n2uil/python-browserstack/commit/e7f6b1f94984db5f7514bdd0baf46885eb0c6a52)
